reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  sequence_diagrams: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: true
    base_branches: ["main"]